# Generated by Django 4.2.3 on 2023-08-29 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_order_account_finishedorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedorder',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 29, 12, 22, 42, 186184, tzinfo=datetime.timezone.utc)),
        ),
    ]
